version: '3.7'

services:

  gjw-web:
    container_name: gjw-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/gjw-web'
      - '/gjw-web/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true